import { StyleSheet } from "react-native";
// --- ESTILOS ---
export const styles = StyleSheet.create({
    safeArea: { 
        flex: 1, 
        backgroundColor: '#f9fafb' 
    },
    container: { 
        padding: 20, 
        paddingBottom: 60,
        gap: 20,
    },
    header: { 
        marginBottom: 4,
        gap: 4,
    },
    headerTitle: { 
        fontSize: 32, 
        fontWeight: '700', 
        color: '#1e3a8a',
        letterSpacing: -0.5,
    },
    headerSubtitle: { 
        fontSize: 15, 
        color: '#6b7280',
        marginTop: 2,
    },
    filterContainer: { 
        flexDirection: 'row', 
        gap: 12, 
        alignItems: 'center',
        marginBottom: 4,
    },
    pickerWrapper: {
        flex: 1,
    },
    pickerContainer: { 
        borderWidth: 1.5, 
        borderColor: '#e5e7eb', 
        borderRadius: 12,
        backgroundColor: '#ffffff',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    picker: {
        height: 50,
    },
    exportButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#eff6ff',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: '#3b82f6',
        gap: 8,
        minWidth: 120,
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    exportIcon: {
        marginRight: -2,
    },
    exportButtonText: {
        color: '#3b82f6',
        fontSize: 15,
        fontWeight: '600',
    },
    tabsContainer: { 
        flexDirection: 'row', 
        gap: 10, 
        paddingVertical: 4,
        paddingHorizontal: 2,
    },
    tab: { 
        paddingVertical: 12, 
        paddingHorizontal: 20, 
        borderRadius: 12, 
        backgroundColor: '#ffffff',
        borderWidth: 1.5,
        borderColor: '#e5e7eb',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    activeTab: { 
        backgroundColor: '#3b82f6',
        borderColor: '#3b82f6',
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    tabText: { 
        color: '#4b5563', 
        fontWeight: '600',
        fontSize: 14,
    },
    activeTabText: { 
        color: '#ffffff',
        fontWeight: '700',
    },
    tabContent: { 
        gap: 20, 
        marginTop: 8,
    },
    card: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
        borderRadius: 16,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#f3f4f6',
        overflow: 'hidden',
    },
    cardHeader: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#111827',
        letterSpacing: -0.3,
    },
    cardContent: {
        padding: 20,
    },
    chart: { 
        marginVertical: 8, 
        borderRadius: 12,
    },
    pieChartContainer: {
        alignItems: 'center',
        paddingVertical: 8,
    },
    financialGrid: { 
        flexDirection: 'row', 
        flexWrap: 'wrap', 
        justifyContent: 'space-between', 
        gap: 12,
    },
    financialBox: { 
        width: '48%', 
        padding: 20, 
        borderRadius: 14, 
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    financialValue: { 
        fontSize: 20, 
        fontWeight: '700',
        marginBottom: 6,
        letterSpacing: -0.5,
    },
    financialLabel: { 
        fontSize: 13, 
        fontWeight: '600',
        textAlign: 'center',
        opacity: 0.85,
    },
});