import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({

    safeArea: { 
        flex: 1, 
        backgroundColor: '#f8fafc' 
    },
    header: { 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'center', 
        padding: 20,
        paddingBottom: 20,
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 3,
        elevation: 2,
    },
    headerTextContainer: {
        flex: 1,
    },
    headerTitle: { 
        fontSize: 28, 
        fontWeight: '700', 
        color: '#1e293b',
        marginBottom: 2,
        letterSpacing: -0.5,
    },
    headerSubtitle: { 
        fontSize: 14, 
        color: '#64748b',
        fontWeight: '500',
    },
    newButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 12,
        shadowColor: '#2563eb',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    buttonIcon: {
        marginRight: 0,
    },
    buttonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 15,
    },
    
    // Search and Filter
    searchFilterContainer: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 16,
        backgroundColor: '#fff',
        gap: 12,
    },
    searchInputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8fafc',
        borderRadius: 12,
        paddingHorizontal: 14,
        height: 50,
        borderWidth: 1.5,
        borderColor: '#e2e8f0',
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 15,
        color: '#0f172a',
        paddingVertical: 0,
        fontWeight: '500',
    },
    searchClearButton: {
        padding: 6,
        marginLeft: 4,
        borderRadius: 8,
        backgroundColor: '#f1f5f9',
    },
    filterPickerContainer: { 
        borderWidth: 1.5, 
        borderColor: '#e2e8f0', 
        borderRadius: 12,
        backgroundColor: '#f8fafc',
        overflow: 'hidden',
    },
    filterPicker: {
        height: 50,
    },
    
    // Status Cards
    statusCardsContainer: {
        flexDirection: 'row',
        padding: 16,
        paddingTop: 16,
        paddingBottom: 16,
        gap: 10,
        backgroundColor: '#f8fafc',
    },
    statusCard: {
        flex: 1,
        padding: 14,
        borderRadius: 16,
        alignItems: 'center',
        gap: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
        elevation: 2,
    },
    statusCardDanger: {
        backgroundColor: '#fef2f2',
        borderWidth: 1,
        borderColor: '#fee2e2',
    },
    statusCardWarning: {
        backgroundColor: '#fffbeb',
        borderWidth: 1,
        borderColor: '#fef3c7',
    },
    statusCardSuccess: {
        backgroundColor: '#f0fdf4',
        borderWidth: 1,
        borderColor: '#dcfce7',
    },
    statusCardNumber: {
        fontSize: 28,
        fontWeight: '700',
        color: '#0f172a',
        letterSpacing: -1,
    },
    statusCardLabel: {
        fontSize: 11,
        color: '#64748b',
        fontWeight: '600',
        textAlign: 'center',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    
    // Tabs
    tabsContainer: { 
        backgroundColor: '#fff',
        borderBottomWidth: 1, 
        borderBottomColor: '#e2e8f0',
        paddingTop: 12,
        marginTop: 4,
    },
    tabsScrollContent: {
        paddingHorizontal: 16,
        gap: 4,
    },
    tab: { 
        paddingVertical: 12, 
        paddingHorizontal: 16,
        marginHorizontal: 2,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        borderRadius: 8,
    },
    activeTab: { 
        backgroundColor: '#eff6ff',
        borderBottomWidth: 2, 
        borderBottomColor: '#3b82f6',
    },
    tabText: { 
        color: '#64748b', 
        fontWeight: '600',
        fontSize: 14,
    },
    activeTabText: { 
        color: '#2563eb',
        fontWeight: '700',
    },
    tabBadge: {
        backgroundColor: '#f1f5f9',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 12,
        minWidth: 24,
        alignItems: 'center',
    },
    activeTabBadge: {
        backgroundColor: '#dbeafe',
    },
    tabBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#64748b',
    },
    activeTabBadgeText: {
        color: '#2563eb',
    },
    
    // List
    list: { 
        padding: 16,
        paddingTop: 20,
        paddingBottom: 32,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 80,
        gap: 12,
    },
    emptyText: { 
        textAlign: 'center', 
        color: '#94a3b8',
        fontSize: 16,
        fontWeight: '600',
    },
    emptySubtext: {
        textAlign: 'center',
        color: '#cbd5e1',
        fontSize: 14,
        maxWidth: 280,
    },
    clearSearchButton: {
        marginTop: 16,
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: '#2563eb',
        borderRadius: 8,
    },
    clearSearchButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    
    // Issue Card
    issueCard: { 
        backgroundColor: '#fff',
        borderRadius: 16,
        borderLeftWidth: 4,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 2,
    },
    issueCardContent: { 
        padding: 16, 
        flexDirection: 'row', 
        alignItems: 'flex-start',
        gap: 12,
    },
    statusIconContainer: {
        marginTop: 2,
        backgroundColor: '#f8fafc',
        padding: 6,
        borderRadius: 10,
    },
    issueCardBody: {
        flex: 1,
        gap: 6,
    },
    issueCardHeader: { 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'flex-start',
        gap: 12,
        marginBottom: 2,
    },
    issueTitle: { 
        fontSize: 16, 
        fontWeight: '700', 
        color: '#0f172a', 
        flex: 1,
        lineHeight: 22,
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 8,
    },
    issueType: {
        fontSize: 12,
        color: '#64748b',
        fontWeight: '600',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    issueDescription: { 
        fontSize: 14, 
        color: '#475569',
        lineHeight: 20,
        marginTop: 4,
    },
    issueMetaContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: '#f1f5f9',
    },
    issueMeta: { 
        fontSize: 12, 
        color: '#64748b',
        fontWeight: '600',
    },
    metaRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    imageIndicator: {
        backgroundColor: '#f1f5f9',
        padding: 5,
        borderRadius: 6,
    },
    issueDate: {
        fontSize: 12,
        color: '#94a3b8',
        fontWeight: '500',
    },
    
    // Modal styles
    modalScrollView: {
        marginVertical: 8,
    },
    formGroup: {
        marginBottom: 22, 
    },
    label: { 
        fontSize: 12, 
        fontWeight: '600', 
        color: '#475569', 
        marginBottom: 8,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    pickerContainer: { 
        borderWidth: 1.5, 
        borderColor: '#e2e8f0', 
        borderRadius: 12,
        backgroundColor: '#f8fafc',
        overflow: 'hidden',
    },
    picker: {
        height: 50,
    },
    imagePreview: {
        width: '100%',
        height: 200,
        borderRadius: 12,
        backgroundColor: '#f1f5f9',
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    cameraButton: { 
        height: 140, 
        borderStyle: 'dashed',
        borderWidth: 2,
        borderColor: '#cbd5e1',
        borderRadius: 16,
        flexDirection: 'column',
        gap: 10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f8fafc',
    },
    cameraButtonText: {
        color: '#64748b',
        fontSize: 15,
        fontWeight: '600',
    },
    modalActions: { 
        flexDirection: 'row', 
        gap: 12,
        marginTop: 24,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f1f5f9',
    },
    modalButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
    },
    cancelButtonText: {
        color: '#475569',
        fontWeight: '700',
        fontSize: 15,
    },
    submitButtonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 15,
    },

    // Detail Modal
    detailScrollView: {
        marginVertical: 16,
    },
    detailStatusHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 18,
        borderRadius: 16,
        marginBottom: 20,
        gap: 14,
    },
    detailStatusIconContainer: {
        backgroundColor: '#fff',
        padding: 10,
        borderRadius: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    detailStatusInfo: {
        flex: 1,
    },
    detailStatusLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 4,
    },
    detailStatusText: {
        fontSize: 22,
        fontWeight: '700',
        letterSpacing: -0.5,
    },
    detailTitleSection: {
        marginBottom: 20,
    },
    detailTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#0f172a',
        lineHeight: 32,
        marginBottom: 10,
        letterSpacing: -0.5,
    },
    detailTypeBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
    },
    detailImageSection: {
        marginBottom: 20,
    },
    detailImage: {
        width: '100%',
        height: 280,
        borderRadius: 16,
        backgroundColor: '#f1f5f9',
    },
    imageLoadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    imageErrorContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#e2e8f0',
        borderStyle: 'dashed',
        gap: 8,
        backgroundColor: '#f8fafc',
    },
    imageErrorText: {
        fontSize: 13,
        color: '#94a3b8',
        fontWeight: '600',
    },
    detailSection: {
        marginBottom: 20,
    },
    detailLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 10,
    },
    detailText: {
        fontSize: 15,
        color: '#334155',
        lineHeight: 24,
    },
    detailInfoGrid: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 20,
    },
    detailInfoCard: {
        flex: 1,
        backgroundColor: '#f8fafc',
        padding: 14,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    detailInfoLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginBottom: 6,
    },
    detailInfoText: {
        fontSize: 13,
        color: '#0f172a',
        fontWeight: '600',
        lineHeight: 18,
    },
    detailUpdateDate: {
        fontSize: 11,
        color: '#94a3b8',
        textAlign: 'center',
        fontStyle: 'italic',
        marginTop: 12,
        fontWeight: '500',
    },
    quickActionsContainer: {
        marginBottom: 20,
        padding: 16,
        backgroundColor: '#f8fafc',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    quickActionsLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: '#64748b',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 12,
    },
    quickActionsButtons: {
        flexDirection: 'row',
        gap: 8,
        flexWrap: 'wrap',
    },
    quickActionButton: {
        flex: 1,
        minWidth: 120,
        flexDirection: 'row',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 10,
        borderWidth: 1.5,
        backgroundColor: '#fff',
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#334155',
    },
    quickActionButtonDestructive: {
        borderColor: '#fca5a5',
        backgroundColor: '#fef2f2',
    },
    quickActionTextDestructive: {
        color: '#b91c1c',
    },

    // Comments Section
    commentsSection: {
        marginTop: 24,
        marginBottom: 16,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    commentsSectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    commentsSectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#0f172a',
    },
    commentsLoading: {
        paddingVertical: 24,
        alignItems: 'center',
    },
    commentsEmpty: {
        paddingVertical: 40,
        alignItems: 'center',
        gap: 6,
    },
    commentsEmptyText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#94a3b8',
    },
    commentsEmptySubtext: {
        fontSize: 12,
        color: '#cbd5e1',
        fontWeight: '500',
    },
    commentsList: {
        gap: 14,
        marginBottom: 16,
    },
    commentItem: {
        flexDirection: 'row',
        gap: 10,
        alignItems: 'flex-start',
    },
    commentAvatar: {
        width: 38,
        height: 38,
        borderRadius: 19,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.15,
        shadowRadius: 2,
        elevation: 2,
    },
    commentAvatarMorador: {
        backgroundColor: '#3b82f6',
    },
    commentAvatarAdmin: {
        backgroundColor: '#10b981',
    },
    commentContent: {
        flex: 1,
        backgroundColor: '#f8fafc',
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#f1f5f9',
    },
    commentHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 6,
        flexWrap: 'wrap',
    },
    commentAuthor: {
        fontSize: 13,
        fontWeight: '700',
        color: '#0f172a',
    },
    adminBadge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        backgroundColor: '#d1fae5',
        borderColor: '#6ee7b7',
        borderRadius: 6,
    },
    adminBadgeText: {
        fontSize: 9,
        fontWeight: '700',
        color: '#065f46',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    commentDate: {
        fontSize: 11,
        color: '#94a3b8',
        marginLeft: 'auto',
        fontWeight: '600',
    },
    commentText: {
        fontSize: 14,
        color: '#475569',
        lineHeight: 20,
    },
    commentInputContainer: {
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f1f5f9',
    },
    commentInputWrapper: {
        flexDirection: 'row',
        gap: 10,
        alignItems: 'flex-end',
    },
    commentInput: {
        flex: 1,
        minHeight: 48,
        maxHeight: 120,
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#fff',
        borderRadius: 24,
        borderWidth: 1.5,
        borderColor: '#e2e8f0',
        fontSize: 15,
        lineHeight: 20,
    },
    commentSendButton: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#3b82f6',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    commentSendButtonDisabled: {
        backgroundColor: '#cbd5e1',
        opacity: 0.7,
        shadowOpacity: 0,
        elevation: 0,
    },
    
    // Footer
    footerLoader: {
        paddingVertical: 20,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
    },
    footerLoaderText: {
        color: '#6b7280',
        fontSize: 14,
        fontWeight: '500',
    },
});